### ISSUE TITLE
A Bishop's Profile View that pulls data from CatholicHierarchy.org

### ISSUE THREAD

**Issue by tjboudreaux** [geerlingguy/Catholic-Diocese-App-iOS#2]
What do you think about a profile view that parses data from a Bishop's page on CatholicHierarchy.org?

**Comment by geerlingguy** [comment]
That may be a nice class to have; I don't know how many dioceses would want that, but the option of adding a tab for the bishop, at a minimum, would be good.

My original plans for the project were to get 4-8 core features in, working really well, as separate classes, and then make it easy for a developer to turn on or off different features they wanted. The current core features are Parishes, News, and Prayers... having a 'Bishop' feature would be nice. Probably also a 'Podcast' feature.
