### ISSUE TITLE
ARC compatibility

### ISSUE THREAD

**Issue by tjboudreaux** [geerlingguy/Catholic-Diocese-App-iOS#3]
It seems that making this ARC compatible would be a wise way to future proof the project.

**Comment by geerlingguy** [comment]
No doubt about that! When I last worked on the app, ARC and Xcode 4 were not even on the horizon. I have so many retains and releases there. I'm guessing we can just throw those out and switch to LLVM.

**Comment by geerlingguy** [comment]
I've pulled in you ARC-compatibility commit to my master branch. Marking this issue as closed. For file reorganization, please let me know what you think needs to be done (I checked out your patch, but I haven't done enough iOS development to know what the standard convention for file structure should be...).
